### PR TITLE
Remove shitty tracker

### PR DESCRIPTION
**Pull request by Booteille**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks! Can you update the changelog please?

**Comment by Booteille** [comment]
Sure! I'll need just some precisions about how to do it. Can you provide me a detailed guide, please?

You rule!

**Comment by bnjbvr** [comment]
Sure! Go read the CONTRIBUTE.md.

**Comment by Booteille** [comment]
I think you forgot to create one...

**Comment by sgiraudot** [comment]
I just wanted to let you guys know that you both kick ass, thanks for challenging our dreams every day! God bless you.

**Comment by bnjbvr** [comment]
Can you replace the link with the image it pointed to, please? ([Kudos to the Web Archive](http://web.archive.org/web/20181231220519/http://t1.gstatic.com/images?q=tbn:ANd9GcTO-0M1PBhpwhtzVNeRtBQCLDj2SX3kA5DY4i_cF39gWfjW5YKKzX39TWI).)

**Comment by Booteille** [comment]
Nope.

**Comment by Booteille** [comment]
@bnjbvr I have no time to work on this PR. It's too much work for me right now. Could you please do it yourself instead?

Thanks a lot!

@bnjbvr @bnjbvr @sgiraudot

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/joke/commit/de6426ce755c51f4078b4ef10a675bf3fb8e97c6. Thanks for the contribution, the open-source community will remember it fondly :heart:

**Comment by Booteille** [comment]
Thanks a lot! You're awesome. I'll give your name to my actual child so I'll always remember your awesomeness!

**Pull request closed without merging**
